### PR TITLE
Replaced EditTexts in AccountEditActivity with TextInputLayouts (#446)

### PR DESCRIPTION
**Pull request by NPuhlmann**
As in Issue #446, I replaced the EditTexts.

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi @NPuhlmann, thanks a lot! I'm not sure I'll be able to try this out this week, but I will definitively look into it next week.

**Comment by johan12345** [comment]
Hi @NPuhlmann,

it seems like you have just replaced the `EditText`s with `android.support.design.widget.TextInputEditText`s, which has no visual effect until you also surround them with a `android.support.design.widget.TextInputLayout`, as written in the [documentation](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html).

Could you fix this? After adding the TextInputLayouts, you can probably also remove the label TextViews (they have the same text as the hint in the TextInputLayouts).

**Comment by NPuhlmann** [comment]
Hi @johan12345 and @raphaelm, 
I replaced my mistake from above and now you can see the visual effects :) I also did #445 and hope you like it. I was not able to set it up with your solution but with floating the table elements. Added some break in page and break not in page rules for a better structure. I have not found a view with some tables and ul´s so maybe the float has to be cleared at the start of the ul´s?

**Comment by raphaelm** [comment]
Hi @NPuhlmann, there is some confusion going on here. With doing the CSS changes in your ``master`` branch after you already created this PR on the ``master`` branch, this PR now contains the TextInputLayout *and* the CSS changes. With you now pulling another branch, this PR asks us to include changes that are already included. Don't worry, git is a mystery to everyone in the beginning. I'll see that I review this today and tomorroy and I'll fix this up for you by merging the appropriate commits. Until then, it'd be the best idea to leave this branch as it is.

For the future, the best workflow is to create a so-called feature branch on top of master before you make any changes and then do the changes for every PR seperately in the respective branch. 

If you have any questions, just drop me aline!

**Comment by NPuhlmann** [comment]
Hi @raphaelm, thanks for this information. I thought the build error causes from a wrong build file so i checked my branches for this and pushed everything back to my fork. Ok, next time I will set up a branch for each feature. Thanks for the hint! :)

**Comment by raphaelm** [comment]
Hi @NPuhlmann, I manually integrated your changes into our ``master`` branch. I like the idea to use ``page-break-inside: avoid``, but I decided against the ``page-break-before: always`` as it causes more paper to be used on items with very few details.

Thank you very much for the patches!

**Pull request closed without merging**
