### PR TITLE
A bunch of miscellaneous upgrades

### PR DESCRIPTION
**Pull request by TacoTheDank**
Sorry this is so big, didn't mean for that.

### 1st commit
- Delete some unnecessary files
- Clean up duplicates in .gitignore

### 2nd commit
- Update gradle wrapper to 6.5 using git bash

### 3rd commit
- Reformat and rearrange gradles to be easier to read
- Update Android Studio 3.6.1 -> 4.0.0 ([changelog](https://developer.android.com/studio/releases))
- Update bintray plugin 2.8.4 -> 2.8.5 ([changelog](https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin#release))
- Update coveralls plugin 2.4.0 -> 2.8.3 ([changelog](https://github.com/kt3k/coveralls-gradle-plugin#release-history))
- Grouped dependencies for easier reading

### 4th commit
- libopac:
  - Updated Jsoup 1.8.3 -> 1.13.1 ([changelog](https://github.com/jhy/jsoup/blob/master/CHANGES))
  - Updated `org.apache.httpcomponents:httpmime` 4.5.2 -> 4.5.12 ([changelog](https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt))
  - Updated joda-time 2.9.9 -> 2.10.6 ([changelog](https://www.joda.org/joda-time/changes-report.html))
  - Updated OkHttp3 versions -> 3.12.12 ([changelog](https://square.github.io/okhttp/changelog_3x/))
  - Updated streamsupport-cfuture 1.6.0 -> 1.7.2 ([changelog](https://github.com/stefan-zobel/streamsupport/releases))
  - Updated JUnit 4.12 -> 4.13 ([changelog](https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md))
    - Fixed deprecations in tests
  - Updated hamcrest-library 1.3 -> 2.2 ([changelog](https://github.com/hamcrest/JavaHamcrest/releases))
    - Fixed deprecations in tests

- meaningdetector:
  - Updated `org.bouncycastle:bcprov-jdk15on` 1.51 -> 1.65.01 ([changelog](https://www.bouncycastle.org/releasenotes.html))

- opacapp:
  - Updated AndroidX Multidex 2.0.0 -> 2.0.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/multidex))
  - Updated sentry-android 1.7.16 -> 1.7.30 (can't find changelog, but nothing broke)
  - Updated Jsoup 1.8.3 -> 1.13.1 ([changelog](https://github.com/jhy/jsoup/blob/master/CHANGES))
  - Updated joda-time 2.9.9 -> 2.10.6 ([changelog](https://www.joda.org/joda-time/changes-report.html))
  - Remove unused joda-convert
  - Updated `su.j2e:rv-joiner` 1.0.6 -> 1.0.9 ([changelog](https://github.com/j2esu/rv-joiner/releases))
  - Updated Updated OkHttp3 versions -> 3.12.12 ([changelog](https://square.github.io/okhttp/changelog_3x/))
  - Remove unused okhttp-urlconnection
  - Updated Retrofit 2.3.0 -> 2.6.4 ([changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md))
  - Updated JMustache 1.13 -> 1.15 ([changelog](https://github.com/samskivert/jmustache/releases))
  - Replace obsolete material-intro fork with its upstream
    - Updated material-intro 1.6 (the fork version) -> 2.0.0 ([changelog](https://github.com/heinrichreimer/material-intro/releases))
  - Remove unused streamsupport-cfuture
  - Updated play-services-safetynet 15.0.1 -> play-services-basement 17.3.0 (where the actual used class is from) ([changelog](https://developers.google.com/android/guides/releases))
  - Updated Stetho 1.5.0 -> 1.5.1 ([changelog](https://github.com/facebook/stetho/releases))
  - Remove unused LeakCanary
  - Updated Mockito 3.2.0 -> 3.3.3 ([changelog](https://github.com/mockito/mockito/releases))
  - Updated JUnit 4.12 -> 4.13 ([changelog](https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md))
  - Updated commons-io 2.5 -> 2.7 ([changelog](https://commons.apache.org/proper/commons-io/))

- tests:
  - Updated JUnit 4.12 -> 4.13 ([changelog](https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md))
  - Updated `org.bouncycastle:bcprov-jdk15on` 1.51 -> 1.65.01 ([changelog](https://www.bouncycastle.org/releasenotes.html))
  - Updated Jsoup 1.8.3 -> 1.13.1 ([changelog](https://github.com/jhy/jsoup/blob/master/CHANGES))

### 5th commit
- Migrate Sentry to 2.x ([changelog](https://github.com/getsentry/sentry-android/blob/master/MIGRATION.md)) (I hope I did it right)

### 6th commit
- Replace deprecated legacy AndroidX

### 7th commit
- Updated AndroidX AppCompat 1.0.2 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Updated AndroidX Preference 1.0.0 -> 1.1.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/preference))
- Updated (and added) AndroidX SwipeRefreshLayout 1.0.0 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout))
- Updated AndroidX Work 2.2.0 -> 2.3.4 ([changelog](https://developer.android.com/jetpack/androidx/releases/work))

### 8th commit
- Replace preference (deprecated in API 29) with AndroidX preference

### 9th commit
- Fix a bunch of other deprecations

### 10th commit
- Fix travis not getting SDK licenses

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Accidentally created before finishing the comment above. Oops.

**Comment by TacoTheDank** [comment]
Done. Fixed travis not getting licenses as well.

**Comment by TacoTheDank** [comment]
So it failed again, but to a different SDK license error. I think that'll have to be on your end.

**Comment by johan12345** [comment]
Hi,
first of all, thank you very much 😍- this must have taken some time to go through all dependencies! 

I started to test the updated version and found a bunch of things:
- The app wasn't starting because Sentry was complaining that the DSN is missing. As we only use Sentry in release builds, this should not happen. I disabled Sentry's auto-init functionality in 27fc34b, which should solve this. We still need to think about how we supply the DSN to Sentry now (previously we used a `sentry.properties` file, which was not checked in to this repo, but that method seems to be deprecated with sentry-android 2.0) -> Cc @raphaelm 
- You removed the `okttp-urlconnection` dependency, but it was actually used in libopac (e.g. in HttpClientFactory:190 referencing the JavaNetCookieJar class). I have re-added the dependency in b2338217.
- In a few places, you have replaced `getDefaultEncoding()` or a hardcoded `"UTF-8"` with `Charsets.UTF_8`. Two problems with this:
    - In some library API's in libopac, `getDefaultEncoding()` might actually return something else than `"UTF-8"`. Replacing it with a fixed `Charsets.UTF_8` might cause problems. Instead, we could put something like `Charset.forName()` inside `getDefaultEncoding()` to convert the String to a `Charset` instance.
    - I am getting crashes due to `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/codec/Charsets;`. It seems that the library including the `Charsets` class is missing.
- The [fork of `material-intro`](https://github.com/johan12345/material-intro/commits/custom_layout_api15) included some layout changes. We should check how the intro looks now with the upstream library and whether we can live with that or need to update our fork.
- I think the Travis build should be fixed now with a08f23f.

**Comment by TacoTheDank** [comment]
@johan12345 Yeah, sorry about all those.

I think sentry needs [this](https://docs.sentry.io/platforms/android/migrate/) to work for 2.x. This migration guide will tell you all about migrating to the new 2.x.

I'll go and fix up the Charset stuff.

**Comment by TacoTheDank** [comment]
@johan12345 It's just because `parse` using String is deprecated for API 22 and up, and it wants people to use charsets instead. I'll revert all those just to be safe.

**Comment by TacoTheDank** [comment]
The built apks still crash with auto-init disabled. I believe the next commit I push will solve this.

**Comment by TacoTheDank** [comment]
@johan12345 What's interesting is that upgrading Sentry to 2.x saves almost a megabyte in APK size (811 KB, the other 300 or so KB is due to other stuff).
image

You can check out exactly the differences by decompiling the APKs with https://github.com/iBotPeaches/Apktool.

**Comment by TacoTheDank** [comment]
@johan12345 Sorry for so many mentions lol, but here's what the material-intro looks like.


This obviously is'nt intended. I'll revert the change for now. You should make a new branch for 2.0.0 and make your own changes on top of it.

**Comment by johan12345** [comment]
@TacoTheDank 

> The built apks still crash with auto-init disabled. 

For the release build? The debug build is working for me now. For the release build we definitely need to supply the DSN. I'll ask @raphaelm how we can do that, maybe we just need to put it in the public repository.

I found one more thing: The tests in `:libopac:tests` were failing with
```
java.lang.NoSuchMethodError: org.hamcrest.Matchers.in(Ljava/util/Collection;)Lorg/hamcrest/Matcher;
```
that is fixed with f786ab2. But now there are some more test failures. That may be due to changes in JSoup, so we need to check what happened there.

**Comment by johan12345** [comment]
@TacoTheDank with 7f6a297 I have emulated the previous Sentry behavior, i.e. loading the DSN from sentry.properties if it exists and ignoring it otherwise.

**Comment by TacoTheDank** [comment]
@johan12345 Awesome 👍

**Comment by johan12345** [comment]
I reverted the JSoup upgrade for now, tests are passing now.

Changes in JSoup are critical, as we are parsing HTML pages of many different library catalogs. We will check the problems occurring with updated JSoup separately.

I will merge this PR now, thanks again to @TacoTheDank !

**Pull request merged**
