### PR TITLE
Added code to display SnackBar - Issue 428

### PR DESCRIPTION
**Pull request by YSulekha**
Hi,
Below are the changes made for Issue #428.
- I have added a method called showSnackBar()  and added a private variable "sItem" in StarredFragment java class.
- I have added two strings "starred_removed" and "starred_removed_undo" in values folder.[I believe you will handle the localization part]
I have tested the changes and it is working fine. Please let me know if there are any changes to be done.

Thanks,
Sulekha

### CODE REVIEW

**Comment by johan12345** [comment]
Hi,
thank you very much for the Pull request! I have just tried it out and it looks fine to me. :smiley: 

Yes, we will handle the localization part (at least for the German version, the others will be done by our contributors on [Transifex](https://www.transifex.com/projects/p/opacapp/)).

Two small remarks:

- Due to a [bug in Android Studio](https://code.google.com/p/android/issues/detail?id=172347), some files in the `opacclient/.idea` folder were deleted when you first opened the project. This is something we did not mention in the documentation (I added it just now) so it's not your fault. Please restore these files by running the following on a command line in the repository:
```
    git checkout HEAD~1 opacclient/.idea/
    git commit --amend
```
Then confirm the displayed commit message and use
```
    git push --force
```
to upload the changes.
- Please go to the code file you changed (`StarredFragment.java`), select the whole code and use Android Studio's "Reformat Code" function (Ctrl+Alt+L). This ensures for example that the length of each line of code is not longer than 100 characters and inserts spaces e.g. after commas in function calls. You can then also upload these changes using 
```
    git commit --amend
    git push --force
```

I'll also wait for a response from @raphaelm before merging the PR to see if he has additional remarks.

Cheers,
Johan

**Comment by raphaelm** [comment]
Hi Sulekha, thank you very much for this pull request. Johan, thank you for reviewing, I agree with your comments and have nothing critical to add, just a small question: This adds the string "UNDO". The capitalizing of the word is not part of the "data" but part of the "design". Should we maybe keep the resource lowercase and make it uppercase when displaying the snackbar (or does Snackbar maybe deal with that already)? This would enable us to re-use the resource in other contexts. On the other hand, uppercasing strings in different locale is a difficult problem by it self and having the uppercase version in the strings enables our translators to cope with this.

**Comment by johan12345** [comment]
It seems that the Snackbar automatically converts its text to uppercase. This means we can simply change the text in the resource file to lowercase without any other code changes.

**Comment by raphaelm** [comment]
In that case, I'm preferring a lower-case string in the resource file. @YSulekha would you mind to adjust this?

**Comment by YSulekha** [comment]
Hi Johan and Raphaelm,

Thanks for the review comment. I will do the below changes and send the pull request in a day.

- Changes related to .idea folder.
- Reformatting the code.
- Change the string "UNDO" to lower case in strings file.

Thanks,
Sulekha

**Comment by YSulekha** [comment]
Hi,

I have incorporated the review changes. Please let me know if there are any changes to be done.

Thanks,
Sulekha

**Comment by raphaelm** [comment]
Hi,
looks good to me! Would you mind to adjust the commit message? You can do this like that:

    git commit --amend -m 'Fix #428: Snackbar and Undo for removing favorites'
    git push --force

After this, I'll go forward with merging the pull request.

**Comment by raphaelm** [comment]
Thank you very much for your contribution! I merged the branch and will include it into the next release!

**Pull request merged**
