### PR TITLE
Print details of a search result #431

### PR DESCRIPTION
**Pull request by ceasarj**
Here is my solution to issue #431

### CODE REVIEW

**Comment by johan12345** [comment]
Hi,
thank you very much for your contribution! I just tried it and it seems to work fine :smiley: 

I just have a few small remarks/questions:

- In line [127](https://github.com/opacapp/opacclient/pull/440/files#diff-8af396bc68eb5928609c9570ec2c47eeR127) of `SearchResultDetailFragment`, it seems you have added a field `private Activity activity;`. For what is this used?
- Did you ensure that the print button is hidden on Android versions before KitKat? You could just insert something like
```java
    menu.findItem(R.id.action_print).setVisible(
            Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT)
```
to the `onCreateOptionsMenu` function.
- Due to a [bug in Android Studio](https://code.google.com/p/android/issues/detail?id=172347), some files in the `opacclient/.idea` folder were deleted when you first opened the project. We also mentioned that in the documentation https://github.com/opacapp/opacclient/wiki/How-to-build-the-project#import-project-in-android-studio. Please restore these files by running the following on a command line in the repository:
```
    git checkout HEAD~3 opacclient/.idea/
```
and then committing and pushing the result.
- Please go to the Java code files you changed (`SearchResultDetailFragment.java`) or added (`PrintUtils.java`), select the whole code and use Android Studio's "Reformat Code" function (Ctrl+Alt+L). This ensures for example that the length of each line of code is not longer than 100 characters and inserts spaces e.g. after commas in function calls or in front of braces of an `if` statement etc.
- After implementing the above changes, you can merge all your commits into one using an interactive Git rebase.

If you'd implement these small changes, I'd be happy to merge your pull request.

**Comment by ceasarj** [comment]
Hi, 
thank you for the feedback. 

- `private Activity activity;` I just deleted it. I was used for nothing.

**Comment by raphaelm** [comment]
Hi @ceasarj!
Because your last comment only responses to one of Johan's points, I just wanted to double-check whether you need any help with the other points or if you just need some more time to get to it. If you do so, please do not hesitate to ask!
I do not want to build up pressure with this, you can take your time as long as you want, this feature is not even remotely urgent – just so we know.
Thanks for your work so far!

**Comment by ceasarj** [comment]
Hi @raphaelm,
I was having trouble merging my commits using gits rebase. But I think I have it figured out. I should finish it up sometime in the next few hours, but if I run into any problems I'll ask for some help.

**Comment by ceasarj** [comment]
Hi @raphaelm and @johan12345, 
I don't know if this would be an adequate place to ask this question but here it is. I've run into a major problem while using gits interactive rebase to merge my commits.

- After implementing the above changes, you can merge all your commits into one using an interactive Git rebase.

1. Here is my log of my last commits
```
ed6acc4 Remarks Modification
5ce39c3 Fixed print_template.mustache formatting
4f759fa Merge branch 'master' of https://github.com/opacapp/opacclient into prin
tResults
2bc035c Added print details function
```

2. Here is when what is shows when I run gits interactive rebase.

```
**pick 2bc035c Added print details function**
pick d4a497c Re-add Bücherhallen Hamburg :)
pick 131e57b Update configuration for Heidelberg
pick 8e9b682 Update GitLab configuration
pick b7c1e83 Get rit dof is_a_redirect and display proper result lists for one result
pick fac0a8f Adis: Fixed problems concerning covers
pick 0385852 OPEN: Fixed restricting by media group
pick b4f4735 Better implementation of SingleResultFound
pick 1e15a11 Changed member visibilites
pick 3872c82 OPEN: Show linked details as well
pick a9e320b OPEN: Fixed extended search
pick 7f6b633 Improved javadoc
pick 18db2aa libopac beta release
pick 9214124 Adis: Improve compatibility with new version (e.g. Berlin)
pick 4ef9697 Fixed config in Siegen, Lemgo, Kreuztal
pick c1e557b Zones: more media types
pick ffbe380 Add: Wülfrath, Porta Westfalica
**pick 5ce39c3 Fixed print_template.mustache formatting
pick ed6acc4 Remarks Modification**
```

From my understanding is that I can't squash ed6acc4 and 5ce39c3 onto 2bc035c without everything. in between.

**Comment by raphaelm** [comment]
Hi @ceasarj,
the cause of the problem is probably that you merged master in between your work. Alternating between merging and rebasing can lead to confusing problems that need to some experience to deal with. For the future, I can recommed you to have a quick look at ``git pull --rebase`` which can make it easier to prepare clean patches against the current upstream code.

To fix your PR, I'd go as following:

```
Create a new branch based of current baster:
$ git checkout master
$ git pull https://github.com/opacapp/opacclient.git master
$ git checkout -b printResults-fixed

Take over the commits:
$ git cherry-pick 2bc035c
Resolve conflict in opacclient/opacapp/build.gradle
$ git add opacclient/opacapp/build.gradle && git commit
$ git cherry-pick 5ce39c3
$ git cherry-pick ed6acc4

Squash commits now:
$ git rebase -i master

Push this into the PR:
$ git push -f printResults-fixed:printResults
```

**Comment by johan12345** [comment]
Hi @ceasarj,
it seems you managed to solve the rebasing problem and the other remarks from my comment, so I merged your PR now. Again, thank you very much for your contribution!

**Pull request merged**
